version: '3.8'

services:
  next-app:
    container_name: tshirt-shop
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/app/src
      - ./public/:/app/public
    restart: always
    ports:
      - 3000:3000
