version: '3.8'

services:
  next-app:
    container_name: tshirt-shop
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend/src/:/app/src
      - ./frontend/public/:/app/public
      - ./frontend:/app
      - /app/node_modules
    restart: always
    ports:
      - 3000:3000
